---
abstract: 'Publish and Subscribe with PubSubHubbub'
author:
  - 'Nils Diewald'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-PubSubHubbub
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 3.43
  Mojolicious::Plugin::Util::Callback: 0.02
  Mojolicious::Plugin::Util::Endpoint: 0.12
  perl: 5.010001
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Akron/Mojolicious-Plugin-PubSubHubbub
version: 0.05
